language: java
jdk:
  - openjdk8

branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2/repository"
script: "mvn package"
before_deploy:
  - zip -r cogather-webservice *
  - mkdir -p deploy
  - mv cogather-webservice.zip deploy/

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # Travis repo settings 에 설정된 값
    secret_access_key: $AWS_SECRET_KEY # 위랑 동일한 곳에 설정됨
    bucket: springboot-practice-build-storage # s3 버킷
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근을 private로
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true
  
notifications:
  email:
    recipients:
      - "qhxmaoflr@gmail.com"