language: java
jdk:
  - openjdk8

branches:
  only:
    - master
cache:
  directories:
    - "$HOME/.m2/repository"
script: "mvn package"

notifications:
  email:
    recipients:
      - "qhxmaoflr@gmail.com"